### ISSUE TITLE
SmartList

### ISSUE THREAD

**Issue by Skonnoth** [PseudoTV/PseudoTV_Live#72]
**Describe the bug**
Using PsedudoTV Live 0.6.0z. On latest Kodi 3.4.0 (PC Win11). SmartLists calling TV shows not listed on the list.

**To Reproduce**

**Expected behavior**
 SmartLists should only calling TV shows listed on the list.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Lunatixz** [comment]
I'm sorry I don't follow, what smart list? Can you give me more details. THX

**Comment by Skonnoth** [comment]
Hi Lunatixz! Thanks for the quick reply...
Ive made a bunch of Video Smart Playlists to organise my tv shows into channels for  PseudoTV_Live.
They seam to work, but every now and then one of the channels will play a tv show that was not originally added to that Video Smart Playlist..
EG: i will be watching the PseudoTV_Live. "Science Fiction TV" channel I made, and a show form the "Lifestyle TV " channel will play.

Also, I just started to get the "Channel stops playing (when show finishes) and returns to kodi menu" bug.
Hope you can help

regards
Paul.


[cid:948361ee-4204-4154-a44f-fdfcac270710]

[cid:3b93a184-2bca-4600-b507-a1af852aa146]
________________________________

**Comment by Lunatixz** [comment]
let me know if its fixed in v.0.6.1

**Comment by Skonnoth** [comment]
Hi There!
The "Channel stops playing (when show finishes) and returns to kodi menu" bug, seems to have stopped so far. I'll keep an eye on this issue.
But the Video Smart Playlists to issue is still there.
Is there a better whey to orgainse the channels?


Regards
Paul

________________________________

**Comment by Lunatixz** [comment]
Have you verifed the smartplaylist only returns the correct entries outside of pseudo?

**Comment by Skonnoth** [comment]
Hi Lunatixz!

I've done some testing with PseudoTV 0.6.1b... Sorry I haven't replied sooner.

I have completed a  Clean reinstall of kodi and rescanned media (with default settings)
Installed PseudoTV 0.6.1b (with default settings)
Built new Video Smart Lists “Lifestyle TV” , "Doctor Who", and  “Anthology TV” for testing PseudoTV live channels

There are still issues 🙁

When I go to live TV in Kodi, the Eletronic Programme Guide is visible
I  then Select a channel, for example , "Anthology TV" channel, Guide says "Comic Strip Present - episode 1 "
Click on channel, TV show starts playing in background but does not switch to full screen (Seet below)
[cid:38f356d4-fadc-44c5-840c-37f09f9fc2f8]
Click on the same channel again, it switches to full screen ,but now plays a different tv show
[cid:21e7d24c-bd66-44b7-a088-f5d31512174b]
Watched the tv show through to the end,
It Auto played new tv show after last show ended, But new tv shows did not start from the beginning (1 started play at 8 mins in and another was 20 min in).
Also, sometimes, the new show auto starts but it doesn't switch to full screen. It just plays behind the TV Channel menu.
 [cid:e7b4d48e-a709-4e25-b139-1314c1b560c6]
And, when I click again it switches to full screen but plays a different show, but with the original shows name.
[cid:976f293e-ee74-4267-bb5d-89cb01cc9834]

Is this an issue with the Video Smart Lists?
I'll try a new PseudoTV live build and use "Video Folder" option to build a channel.
Unless you know of a better recommendation?


[cid:935fe217-3355-4fb7-bda6-88fe39190f9b]

regards
Paul

________________________________

**Comment by Lunatixz** [comment]
I'll require a log: https://github.com/PseudoTV/PseudoTV_Live/wiki/Support#reporting-issues
